theme = "ayu_evolve"

[editor]
mouse = false
line-number = "relative"
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["file-encoding", "file-line-ending", "file-type",]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
# display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = ["extend_line_above"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
tab = "goto_next_buffer"
S-tab = "goto_previous_buffer"
C-v = ":vs"
C-h = "jump_view_left"
C-l = "jump_view_right"

[keys.normal.space]
x = ":bc"
m = ":format"

[keys.insert]
"C-c" = "normal_mode"
"C-h" = "move_char_left"
"C-j" = "move_line_down"
"C-k" = "move_line_up"
"C-l" = "move_char_right"
